#!/usr/bin/env bash

export GOPATH=/opt/gopkg
export GOROOT=/opt/go
export PATH=$GOROOT/bin:$GOPATH/bin:$PATH

function remote_test_dependencies() {
    # !!! This test fails frequently !!!
    cd "${GOPATH}/src/github.com/gravitational/teleport/lib/client"           && go test ./...

    # ---

    cd "${GOPATH}/src/github.com/gravitational/teleport/process"              && go test ./...
    cd "${GOPATH}/src/github.com/gravitational/teleport/lib/auth"             && go test ./...
    cd "${GOPATH}/src/github.com/gravitational/teleport/lib/config"           && go test ./...
    cd "${GOPATH}/src/github.com/gravitational/teleport/lib/defaults"         && go test ./...
    cd "${GOPATH}/src/github.com/gravitational/teleport/lib/events"           && go test ./...
    cd "${GOPATH}/src/github.com/gravitational/teleport/lib/httplib"          && go test ./...
    cd "${GOPATH}/src/github.com/gravitational/teleport/lib/limiter"          && go test ./...
    cd "${GOPATH}/src/github.com/gravitational/teleport/lib/reversetunnel"    && go test ./...
    cd "${GOPATH}/src/github.com/gravitational/teleport/lib/service"          && go test ./...
    cd "${GOPATH}/src/github.com/gravitational/teleport/lib/services"         && go test ./...
    cd "${GOPATH}/src/github.com/gravitational/teleport/lib/session"          && go test ./...
    cd "${GOPATH}/src/github.com/gravitational/teleport/lib/srv"              && go test ./...
    cd "${GOPATH}/src/github.com/gravitational/teleport/lib/sshutils"         && go test ./...
    cd "${GOPATH}/src/github.com/gravitational/teleport/lib/teleagent"        && go test ./...
    cd "${GOPATH}/src/github.com/gravitational/teleport/lib/utils"            && go test ./...
    cd "${GOPATH}/src/github.com/gravitational/teleport/lib/web"              && go test ./...
    cd "${GOPATH}/src/github.com/stkim1/pc-node-agent"                        && go test ./...

#    cd "${GOPATH}/src/github.com/gravitational/teleport/integration"         && go test ./...
#    cd "${GOPATH}/src/github.com/gravitational/teleport/lib/backend"         && go test ./...
}

remote_test_dependencies