#!/usr/bin/env bash

#set -ex

GOREPO=${GOREPO:-"${HOME}/Workspace/POCKETPKG"}
GOPATH=${GOPATH:-"${GOREPO}:$GOWORKPLACE"}
PATH=${PATH:-"$GEM_HOME/ruby/2.0.0/bin:$HOME/.util:$GOROOT/bin:$GOREPO/bin:$GOWORKPLACE/bin:$HOME/.util:$NATIVE_PATH"}
WORK_ROOT=${WORK_ROOT:-"${GOREPO}/DEPSETUP"}
ADV_TESTGO=${ADV_TESTGO:-0}

# Testing teleport
:<<STATIC_HOST_JOIN_FAIL
* This fails at the first attempt, but succeed in the subsequent one
----------------------------------------------------------------------
FAIL: tun_test.go:425: TunSuite.TestSync

tun_test.go:461:
    c.Assert(syncedServers, DeepEquals, discoveredServers)
... obtained []utils.NetAddr = []utils.NetAddr(nil)
... expected []utils.NetAddr = []utils.NetAddr{utils.NetAddr{Addr:"node.example.com:12345", AddrNetwork:"tcp", Path:""}}

OOPS: 20 passed, 1 FAILED
--- FAIL: TestAPI (5.94s)
STATIC_HOST_JOIN_FAIL

function test_dependencies {
    pushd ${WORK_ROOT}
    echo "Starting testing..."
    cd "${GOREPO}/src/github.com/gravitational/teleport/integration"    && go test ./...
    cd "${GOREPO}/src/github.com/gravitational/teleport/process"        && go test ./...
    cd "${GOREPO}/src/github.com/gravitational/teleport/lib"            && go test ./...

    # Testing etcd
    if [[ ${ADV_TESTGO} -eq 1 ]];then
    # it passes but it takes long, 266.584s
        cd "${GOREPO}/src/github.com/coreos/etcd/integration/"          && go test ./...
    fi
    # !!! some tests in v3 client does not pass  !!!
    # cd "${GOREPO}/src/github.com/coreos/etcd/clientv3/"               && go test ./...
    cd "${GOREPO}/src/github.com/coreos/etcd/auth/"                     && go test ./...
    cd "${GOREPO}/src/github.com/coreos/etcd/client/"                   && go test ./...
    cd "${GOREPO}/src/github.com/coreos/etcd/compactor/"                && go test ./...
    cd "${GOREPO}/src/github.com/coreos/etcd/contrib/"                  && go test ./...
    cd "${GOREPO}/src/github.com/coreos/etcd/discovery/"                && go test ./...
    cd "${GOREPO}/src/github.com/coreos/etcd/embed/"                    && go test ./...
    cd "${GOREPO}/src/github.com/coreos/etcd/error/"                    && go test ./...
    cd "${GOREPO}/src/github.com/coreos/etcd/etcdserver/"               && go test ./...
    cd "${GOREPO}/src/github.com/coreos/etcd/lease/"                    && go test ./...
    cd "${GOREPO}/src/github.com/coreos/etcd/mvcc/"                     && go test ./...
    cd "${GOREPO}/src/github.com/coreos/etcd/pkg/"                      && go test ./...
    cd "${GOREPO}/src/github.com/coreos/etcd/proxy/"                    && go test ./...
    cd "${GOREPO}/src/github.com/coreos/etcd/raft/"                     && go test ./...
    cd "${GOREPO}/src/github.com/coreos/etcd/rafthttp/"                 && go test ./...
    cd "${GOREPO}/src/github.com/coreos/etcd/snap/"                     && go test ./...
    cd "${GOREPO}/src/github.com/coreos/etcd/store/"                    && go test ./...
    cd "${GOREPO}/src/github.com/coreos/etcd/wal/"                      && go test ./...

    # Testing swarm
    cd "${GOREPO}/src/github.com/docker/swarm/cluster/"                 && go test ./...
    cd "${GOREPO}/src/github.com/docker/swarm/api/"                     && go test ./...
    cd "${GOREPO}/src/github.com/docker/swarm/discovery/"               && go test ./...
    cd "${GOREPO}/src/github.com/docker/swarm/scheduler/"               && go test ./...

    # Testing libcompose
    if [[ ${ADV_TESTGO} -eq 1 ]];then
    # we need an actual docker daemon running for integration test
        cd "${GOREPO}/src/github.com/docker/libcompose/integration/"    && go test ./...
    fi
    cd "${GOREPO}/src/github.com/docker/libcompose/test/"               && go test ./...
    cd "${GOREPO}/src/github.com/docker/libcompose/docker/"             && go test ./...
    cd "${GOREPO}/src/github.com/docker/libcompose/config/"             && go test ./...
    cd "${GOREPO}/src/github.com/docker/libcompose/labels/"             && go test ./...
    cd "${GOREPO}/src/github.com/docker/libcompose/logger/"             && go test ./...
    cd "${GOREPO}/src/github.com/docker/libcompose/lookup/"             && go test ./...
    cd "${GOREPO}/src/github.com/docker/libcompose/project/"            && go test ./...
    cd "${GOREPO}/src/github.com/docker/libcompose/utils/"              && go test ./...
    cd "${GOREPO}/src/github.com/docker/libcompose/version/"            && go test ./...
    cd "${GOREPO}/src/github.com/docker/libcompose/yaml/"               && go test ./...

    # Testing distribution
    if [[ ${ADV_TESTGO} -eq 1 ]];then
    # github.com/docker/distribution/registry/storage/driver/inmemory takes too long to test
        cd "${GOREPO}/src/github.com/docker/distribution/registry"      && go test ./...
    fi
    cd "${GOREPO}/src/github.com/docker/distribution/configuration"     && go test ./...
    cd "${GOREPO}/src/github.com/docker/distribution/context"           && go test ./...
    cd "${GOREPO}/src/github.com/docker/distribution/digest"            && go test ./...
    cd "${GOREPO}/src/github.com/docker/distribution/health"            && go test ./...
    cd "${GOREPO}/src/github.com/docker/distribution/manifest"          && go test ./...
    cd "${GOREPO}/src/github.com/docker/distribution/notifications"     && go test ./...
    cd "${GOREPO}/src/github.com/docker/distribution/reference"         && go test ./...
    cd "${GOREPO}/src/github.com/docker/distribution/testutil"          && go test ./...
    cd "${GOREPO}/src/github.com/docker/distribution/uuid"              && go test ./...
    cd "${GOREPO}/src/github.com/docker/distribution/version"           && go test ./...

    echo "Testing Done!"
    popd
}

test_dependencies