#!/usr/bin/env bash

function clean_vendor() {
	rm -rf github.com/docker/go-units
	rm -rf golang.org/x/crypto
	rm -rf github.com/docker/leadership
	rm -rf github.com/gogo/protobuf
	rm -rf gopkg.in/check.v1
	rm -rf golang.org/x/sys
	rm -rf github.com/stretchr/testify
	rm -rf github.com/coreos/pkg
	rm -rf github.com/pborman/uuid
	rm -rf github.com/coreos/go-systemd
	rm -rf github.com/docker/docker
	rm -rf google.golang.org/grpc
	rm -rf github.com/ugorji/go
	rm -rf github.com/pkg/errors
	rm -rf golang.org/x/time
	rm -rf github.com/coreos/etcd
	rm -rf github.com/spf13/cobra
	rm -rf golang.org/x/net
	rm -rf github.com/gorilla/context
	rm -rf github.com/stretchr/objx
	rm -rf github.com/docker/distribution
	rm -rf github.com/pmezard/go-difflib
	rm -rf github.com/urfave/cli
	rm -rf github.com/golang/protobuf
	rm -rf github.com/jonboulle/clockwork
	rm -rf github.com/spf13/pflag
	rm -rf gopkg.in/yaml.v2
	rm -rf github.com/opencontainers/runc
	rm -rf github.com/gorilla/mux
	rm -rf github.com/Sirupsen/logrus
	rm -rf github.com/docker/go-connections
	rm -rf github.com/davecgh/go-spew
	rm -rf github.com/Microsoft/go-winio
	rm -rf github.com/boltdb/bolt
	rm -rf github.com/kr/pty
	rm -rf github.com/coreos/etcd
	rm -rf github.com/docker/libcompose
	rm -rf github.com/docker/swarm
	rm -rf github.com/docker/distribution
	rm -rf github.com/gravitational/teleport
}

function cleanup_gopath() {
	rm -rf github.com/hashicorp/serf
	rm -rf github.com/mailgun/minheap
	rm -rf github.com/skarademir/naturalsort
	rm -rf github.com/yvasiyarov/go-metrics
	rm -rf github.com/mailgun/ttlmap
	rm -rf github.com/aws/aws-sdk-go
	rm -rf github.com/docker/libkv
	rm -rf github.com/kardianos/osext
	rm -rf github.com/mailgun/lemma
	rm -rf github.com/samuel/go-zookeeper
	rm -rf github.com/garyburd/redigo
	rm -rf github.com/grpc-ecosystem/grpc-gateway
	rm -rf github.com/julienschmidt/httprouter
	rm -rf github.com/bugsnag/panicwrap
	rm -rf github.com/mailgun/timetools
	rm -rf github.com/bugsnag/bugsnag-go
	rm -rf github.com/karlseguin/ccache
	rm -rf github.com/cpuguy83/go-md2man
	rm -rf github.com/mdp/rsc
	rm -rf github.com/inconshreveable/mousetrap
	rm -rf google.golang.org/api
	rm -rf github.com/denverdino/aliyungo
	rm -rf github.com/docker/goamz
	rm -rf github.com/vulcand/oxy
	rm -rf github.com/coreos/go-oidc
	rm -rf github.com/flynn/go-shlex
	rm -rf github.com/cloudflare/cfssl
	rm -rf github.com/google/btree
	rm -rf rsc.io/letsencrypt
	rm -rf github.com/alecthomas/template
	rm -rf github.com/jinzhu/gorm
	rm -rf github.com/coreos/go-semver
	rm -rf golang.org/x/oauth2
	rm -rf github.com/mattn/go-sqlite3
	rm -rf github.com/docker/libtrust
	rm -rf github.com/stevvooe/resumable
	rm -rf github.com/ncw/swift
	rm -rf github.com/bugsnag/osext
	rm -rf github.com/buger/goterm
	rm -rf github.com/gravitational/kingpin
	rm -rf github.com/mailgun/oxy
	rm -rf github.com/golang/glog
	rm -rf github.com/olekukonko/tablewriter
	rm -rf github.com/Azure/go-ansiterm
	rm -rf golang.org/x/text
	rm -rf github.com/codegangsta/cli
	rm -rf github.com/yvasiyarov/newrelic_platform_go
	rm -rf github.com/dustin/go-humanize
	rm -rf github.com/mitchellh/mapstructure
	rm -rf google.golang.org/appengine
	rm -rf github.com/gravitational/ttlmap
	rm -rf github.com/gravitational/trace
	rm -rf github.com/gorilla/handlers
	rm -rf github.com/bgentry/speakeasy
	rm -rf github.com/mesos/mesos-go
	rm -rf github.com/samalba/dockerclient
	rm -rf github.com/xiang90/probing
	rm -rf github.com/prometheus/client_golang
	rm -rf github.com/mattn/go-shellwords
	rm -rf gopkg.in/cheggaaa/pb.v1
	rm -rf github.com/alecthomas/units
	rm -rf github.com/gravitational/configure
	rm -rf github.com/ghodss/yaml
	rm -rf github.com/mailgun/metrics
	rm -rf github.com/vbatts/tar-split
	rm -rf github.com/xeipuuv/gojsonschema
	rm -rf github.com/cockroachdb/cmux
	rm -rf github.com/Azure/azure-sdk-for-go
	rm -rf github.com/xeipuuv/gojsonreference
	rm -rf github.com/grpc-ecosystem/go-grpc-prometheus
	rm -rf github.com/gravitational/roundtrip
	rm -rf github.com/hashicorp/go-cleanhttp
	rm -rf github.com/gokyle/hotp
	rm -rf gopkg.in/vmihailenco/msgpack.v2
	rm -rf google.golang.org/cloud
	rm -rf github.com/hashicorp/consul
	rm -rf github.com/xeipuuv/gojsonpointer
	rm -rf github.com/yvasiyarov/gorelic
}
